Preparing for flutter_map v6
TesteurManiak/flutter_map_animations pull request #9
Opened 2023-07-05 08:36 UTC by rorystephenson

@TesteurManiak I'm trying my own packages against the proposed flutter_map refactor branch and since some of my packages use this one in the examples I have started migrating it as well. I'm not sure how you want to handle deprecations and whether you want to deprecate the `centerOnPoints` method or not, in any case I figured I'd open this PR in case the changes can be useful when v6 is eventually released.

2023-07-05 11:56 UTC, TesteurManiak requested changes
Thanks for the contribution 😄 
I'm okay with the deprecation of the methods `animatedFitBounds` and `centerOnPoints`. Got a minor remark on the coding style but otherwise this PR seems good to me and I'll merge it once the v6 will be released 👍

2023-07-05 11:56 UTC, TesteurManiak commented on lib/src/animated_map_controller.dart
> +      begin: mapController.camera.zoom,
Maybe directly create a variable that would hold `mapController.camera` to reduce verbosity:
```dart
final camera = mapController.camera;

final effectiveDest = dest ?? camera.center;
final effectiveZoom = zoom ?? camera.zoom;
```

2023-07-05 13:21 UTC, rorystephenson commented
My pleasure, I've made that change so this is ready once v6 is released.

2023-07-05 13:23 UTC, TesteurManiak approved these changes

2023-07-11 10:03 UTC, rorystephenson commented
@TesteurManiak I've changed the dependency from by branch to 6.0.0-dev.1. In doing so it changed the example's pubspec.lock flutter version constraint to >= 3.10.0. Not 100% why, I've left it there but feel free to change it.

2023-08-03 15:54 UTC, merged